def match_info(match) -> dict:
    return{
        "gameMode": match['gameMode'],
        "matchId": match['matchId'],

        "summonerOnePuuid": match['summonerOnePuuid'],
        "summonerTwoPuuid": match['summonerTwoPuuid'],
        "summonerThreePuuid": match['summonerThreePuuid'],
        "summonerFourPuuid": match['summonerFourPuuid'],
        "summonerFivePuuid": match['summonerFivePuuid'],
        "summonerSixPuuid": match['summonerSixPuuid'],
        "summonerSevenPuuid": match['summonerSevenPuuid'],
        "summonerEightPuuid": match['summonerEightPuuid'],
        "summonerNinePuuid": match['summonerNinePuuid'],
        "summonerTenPuuid": match['summonerTenPuuid'],

        "teamBlueId": match['teamBlueId'],
        "teamBlueBan": list(match[i]['championId'] for i in range(5)),
        "teamBlueWin": match['teamBlueWin'],
        "teamBlueGold": match['teamBlueGold'],
        "teamBlueBaronKills": match['teamBlueBaronKills'],
        "teamBlueChampionKills": match['teamBlueChampionKills'],
        "teamBlueDragonKills": match['teamBlueDragonKills'],
        "teamBlueInhibitorKills": match['teamBlueInhibitorKills'],
        "teamBlueRiftheraldKills": match['teamBlueRiftheraldKills'],
        "teamBlueTowerKills": match['teamBlueTowerKills'],

        "teamPurpleId": match['teamPurpleId'],
        "teamPurpleBan": list(match[i]['championId'] for i in range(5)),
        "teamPurpleWin": match['teamPurpleWin'],
        "teamPurpleGold": match['teamPurpleGold'],
        "teamPurpleBaronKills": match['teamPurpleBaronKills'],
        "teamPurpleChampionKills": match['teamPurpleChampionKills'],
        "teamPurpleDragonKills": match['teamPurpleDragonKills'],
        "teamPurpleInhibitorKills": match['teamPurpleInhibitorKills'],
        "teamPurpleRiftheraldKills": match['teamPurpleRiftheraldKills'],
        "teamPurpleTowerKills": match['teamPurpleTowerKills']
    }

def summoner_info(summoner) -> dict:
    return{
        "matchId": summoner['matchId'],
        "assists": summoner['assists'],
        "champLevel": summoner['champLevel'],
        "championId": summoner['championId'],
        "championName": summoner['championName'],
        "deaths": summoner['deaths'],
        "goldEarned": summoner['goldEarned'],
        "goldSpent": summoner['goldSpent'],
        "kills": summoner['kills'],
        "lane": summoner['lane'],
        "summonerName": summoner['summonerName'],
        "riotIdTagline": summoner['riotIdTagline'],
        "role": summoner['role'],
        "teamId": summoner['teamId'],
        "totalDamageDealtToChampions": summoner['totalDamageDealtToChampions'],
        "totalHeal": summoner['totalHeal'],
        "totalTimeCCDealt": summoner['totalTimeCCDealt'],
        "win": summoner['win'],
        "visionScore": summoner['visionScore'],
        "versusassists": summoner['versusassists'],
        "versuschampionLevel" :summoner['versuschampionLevel'],
        "versusdeaths":summoner['versusdeaths'],
        "versusgoldEarned":summoner['versusgoldEarned'],
        "versuskills":summoner['versuskills'],
        "versusTDDTC":summoner['versusTDDTC'],
        "versusTH":summoner['versusTH'],
        "versusTTCCD":summoner['versusTTCCD'],
        "versusVS": summoner['versusVS'],
    }